name: Build and scan Docker Image
on: [push]
# Env variable
env:
  DOCKER_USER: onk2e
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: cicdtest
  REGISTRY_HOST: "docker.io"
  REGISTRY_USER: onk2e
  IMAGE_NAME: "cicdtest"
  DOCKERFILE_CONTEXT: "dummy-vuln-app-master/"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Get current date # get the date of the build
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Get current date # get the date of the build
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"
    
    - name: Build and save
      uses: docker/build-push-action@v3
      with:
        context: ${{ env.DOCKERFILE_CONTEXT }}
        tags: ${{ env.REGISTRY_HOST }}/${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:sysdig-${{ steps.date.outputs.date }}
        load: true      
          
    #- name: Build the Docker image
    #  run: docker build . --file dummy-vuln-app-master/Dockerfile --tag $DOCKER_USER/$REPO_NAME:lw-${{ steps.date.outputs.date }} # Bad image

    - name: Scan container image for vulnerabitilies using Lacework
      uses: lacework/lw-scanner-action@v1.0.0
      with:
        LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }} 
        LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
        #IMAGE_NAME: onk2e/cicdtest
        IMAGE_NAME: ${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}
        IMAGE_TAG: lw-${{ steps.date.outputs.date }}

    - name: docker login
      run: | # log into docker hub account
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: Docker Push
      run: docker push $DOCKER_USER/$REPO_NAME:lw-${{ steps.date.outputs.date }}

